version: 2
updates:
  - package-ecosystem: pip
    directory: /ai-service
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /web
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /ai-service
    schedule:
      interval: weekly
